export const POLLINATIONS_TEXT_MODELS = [
  {
    id: "openai",
    name: "OpenAI GPT-5 Nano",
    provider: "OpenAI via Pollinations",
    description: "Balanced general-purpose model with text and image understanding routed through Pollinations.",
    tier: "anonymous",
    community: false,
    input: ["text", "image"],
    output: ["text"],
    tools: true,
    vision: true,
    audio: false,
    reasoning: false,
    aliases: ["gpt-5-mini"],
  },
  {
    id: "openai-fast",
    name: "OpenAI GPT-4.1 Nano",
    provider: "OpenAI via Pollinations",
    description: "Lower-latency GPT-4.1 Nano variant for quick responses.",
    tier: "anonymous",
    community: false,
    input: ["text", "image"],
    output: ["text"],
    tools: true,
    vision: true,
    audio: false,
    reasoning: false,
    aliases: ["gpt-5-nano"],
  },
  {
    id: "openai-large",
    name: "OpenAI GPT-5 Chat",
    provider: "OpenAI via Pollinations",
    description: "Larger conversational model tuned for richer reasoning and context windows.",
    tier: "seed",
    community: false,
    input: ["text", "image"],
    output: ["text"],
    tools: true,
    vision: true,
    audio: false,
    reasoning: false,
    aliases: ["gpt-5-chat"],
  },
  {
    id: "openai-reasoning",
    name: "OpenAI o4 Mini",
    provider: "OpenAI via Pollinations",
    description: "Reasoning-focused model (o4 Mini) with tool support.",
    tier: "seed",
    community: false,
    input: ["text", "image"],
    output: ["text"],
    tools: true,
    vision: true,
    audio: false,
    reasoning: true,
    aliases: ["o4-mini"],
  },
  {
    id: "openai-audio",
    name: "OpenAI GPT-4o Mini Audio",
    provider: "OpenAI via Pollinations",
    description: "Multimodal GPT-4o Mini preview that can return audio clips.",
    tier: "seed",
    community: false,
    input: ["text", "image", "audio"],
    output: ["audio", "text"],
    tools: true,
    vision: true,
    audio: true,
    reasoning: false,
    aliases: ["gpt-4o-mini-audio-preview"],
    voices: ["alloy", "echo", "fable", "onyx", "nova", "shimmer", "coral", "verse", "ballad", "ash", "sage", "amuch", "dan"],
  },
  {
    id: "deepseek",
    name: "DeepSeek V3.1",
    provider: "DeepSeek",
    description: "Large reasoning model with 10k character context and tool support.",
    tier: "seed",
    community: false,
    input: ["text"],
    output: ["text"],
    tools: true,
    vision: false,
    audio: false,
    reasoning: true,
    aliases: ["deepseek-v3", "deepseek-v3.1", "deepseek-reasoning", "deepseek-r1-0528"],
    maxInputChars: 10000,
  },
  {
    id: "mistral",
    name: "Mistral Small 3.2",
    provider: "Mistral",
    description: "Compact 24B Mistral Small 3.2 instruct model.",
    tier: "anonymous",
    community: false,
    input: ["text"],
    output: ["text"],
    tools: true,
    vision: false,
    audio: false,
    reasoning: false,
    aliases: ["mistral-small-3.1-24b-instruct", "mistral-small-3.1-24b-instruct-2503", "mistral-small-3.2-24b-instruct-2506"],
  },
  {
    id: "gemini",
    name: "Gemini 2.5 Flash Lite",
    provider: "Google",
    description: "Multimodal Gemini Flash Lite with fast responses and tool support.",
    tier: "seed",
    community: false,
    input: ["text", "image"],
    output: ["text"],
    tools: true,
    vision: true,
    audio: false,
    reasoning: false,
    aliases: ["gemini-2.5-flash-lite"],
  },
  {
    id: "gemini-search",
    name: "Gemini Flash + Search",
    provider: "Google",
    description: "Gemini Flash Lite augmented with Google Search integration.",
    tier: "seed",
    community: false,
    input: ["text", "image"],
    output: ["text"],
    tools: true,
    vision: true,
    audio: false,
    reasoning: false,
    aliases: ["searchgpt", "geminisearch"],
  },
  {
    id: "qwen-coder",
    name: "Qwen 2.5 Coder 32B",
    provider: "Alibaba",
    description: "32B Qwen 2.5 coding assistant tuned for development workflows.",
    tier: "anonymous",
    community: false,
    input: ["text"],
    output: ["text"],
    tools: true,
    vision: false,
    audio: false,
    reasoning: false,
    aliases: ["qwen2.5-coder-32b-instruct"],
  },
  {
    id: "roblox-rp",
    name: "Llama 3.1 8B Instruct",
    provider: "Meta",
    description: "Lightweight Llama 3.1 instruct model (Pollinations Roblox RP variant).",
    tier: "seed",
    community: false,
    input: ["text"],
    output: ["text"],
    tools: true,
    vision: false,
    audio: false,
    reasoning: false,
    aliases: ["llama-roblox", "llama-fast-roblox"],
  },
  {
    id: "bidara",
    name: "BIDARA Research Assistant",
    provider: "NASA Community",
    description: "Biomimetic Designer and Research Assistant (community model curated by NASA).",
    tier: "anonymous",
    community: true,
    input: ["text", "image"],
    output: ["text"],
    tools: true,
    vision: true,
    audio: false,
    reasoning: false,
    aliases: [],
  },
  {
    id: "chickytutor",
    name: "ChickyTutor Language Tutor",
    provider: "Community",
    description: "Language tutoring assistant from the ChickyTutor community.",
    tier: "anonymous",
    community: true,
    input: ["text"],
    output: ["text"],
    tools: true,
    vision: false,
    audio: false,
    reasoning: false,
    aliases: [],
  },
  {
    id: "evil",
    name: "Evil (Uncensored)",
    provider: "Community",
    description: "Uncensored community model (use with caution).",
    tier: "seed",
    community: true,
    input: ["text", "image"],
    output: ["text"],
    tools: true,
    vision: true,
    audio: false,
    reasoning: false,
    aliases: [],
    uncensored: true,
  },
  {
    id: "midijourney",
    name: "MIDIjourney",
    provider: "Community",
    description: "Community MIDI/music oriented assistant.",
    tier: "anonymous",
    community: true,
    input: ["text"],
    output: ["text"],
    tools: true,
    vision: false,
    audio: false,
    reasoning: false,
    aliases: [],
  },
  {
    id: "rtist",
    name: "Rtist",
    provider: "Community",
    description: "Creative assistant for artistic brainstorming.",
    tier: "seed",
    community: true,
    input: ["text"],
    output: ["text"],
    tools: true,
    vision: false,
    audio: false,
    reasoning: false,
    aliases: [],
  },
  {
    id: "unity",
    name: "Unity Unrestricted Agent",
    provider: "Community",
    description: "Unrestricted community agent with multimodal support.",
    tier: "seed",
    community: true,
    input: ["text", "image"],
    output: ["text"],
    tools: true,
    vision: true,
    audio: false,
    reasoning: false,
    aliases: [],
    uncensored: true,
  },
]

export const POLLINATIONS_IMAGE_MODELS = [
  {
    id: "flux",
    name: "Flux",
    provider: "Pollinations",
    description: "Default Pollinations image model for high-quality general purpose generations.",
  },
  {
    id: "kontext",
    name: "Kontext",
    provider: "Pollinations",
    description: "Context-aware image model tuned for storytelling scenes.",
  },
  {
    id: "turbo",
    name: "Turbo",
    provider: "Pollinations",
    description: "Fast image generation model optimized for quick previews.",
  },
  {
    id: "gptimage",
    name: "GPT Image",
    provider: "Pollinations",
    description: "GPT-style image model supporting natural language prompts.",
  },
]

export const DEFAULT_TEXT_MODEL_ID = POLLINATIONS_TEXT_MODELS[0].id
export const DEFAULT_IMAGE_MODEL_ID = POLLINATIONS_IMAGE_MODELS[0].id
